object_type: color_notes
difficulty: Easy
log_dir: ./logs
lr: 0.0001
train_batch_size: 14
songs_batch_size: 20
enable_condition: true
seq_length: 16000
skip_step: 2000
with_beats: true
num_layers: 2
dropout: 0.5
rnn_dropout: 0.0
loss_interval: 100
checkpoint_interval: 400
validation_interval: 100
fuzzy_scale: 0.2
fuzzy_width: 5
lr_find: true
end_lr: 1e-7
start_lr: 1e-1
epoch_length: 100
warmup_steps: 200
epochs: 100
wandb_mode: disabled #disabled, online, offline, 
is_parallel: false