method: bayes
metric:
  goal: minimize
  name: validation/loss
parameters:
  model.start_lr:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.001

  model.eta_min:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.0001

  model.weight_decay:
    distribution: log_uniform_values
    min: 0.00000001
    max: 0.001

program: sweep_main.py

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
