method: bayes
metric:
  goal: minimize
  name: train/loss-onset
parameters:
  warmup_steps:
    values: [400, 800]
  epoch_length:
    value: 400
  fuzzy_width:
    min: 2
    max: 6
    distribution: int_uniform
  fuzzy_scale:
    min: 0.1
    max: 0.7
    q: 0.1
    distribution: q_uniform
  start_lr:
    min: 1e-6
    max: 9e-4
    distribution: uniform
  end_lr:
    min: 9e-4
    max: 4e-3
    distribution: uniform
  dropout:
    max: 0.5
    min: 0.0
    q: 0.1
    distribution: q_uniform
  lr_scheduler_name:
    values: [CyclicLR, CosineAnnealingLR]
  rnn_dropout:  
    max: 0.5
    min: 0.0
    q: 0.1
    distribution: q_uniform
  weight_decay:
    max: 1e-6
    min: 0.0
    distribution: uniform
  object_type:  
    value: color_notes
  difficulty:  
    value: Easy
  log_dir:  
    value: ./logs
  train_batch_size: 
    value: 30
  enable_condition: 
    value: true
  seq_length: 
    value: 16000
  skip_step:  
    value: 2000
  with_beats: 
    value: true
  num_layers:  
    value: 2
  loss_interval:  
    value: 100
  checkpoint_interval:  
    value: 400
  validation_interval:  
    value: 1
  epochs: 
    value: 10
  is_parallel: 
    value: true
  save_valid_dataset: 
    value: false
  eta_min: 
    value: 1e-6
