method: bayes
metric:
  goal: maximize
  name: validation/f1_macro
  parameters:
    model.focal_loss_gamma:
      distribution: log_uniform_values
      min: 0.5
      max: 5.0

    model.focal_loss_alpha:
      distribution: log_uniform_values
      min: 0.1
      max: 10.0

program: sweep_main.py

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
